#!/bin/bash
#SBATCH --job-name=FFNN_MPI
#SBATCH --ntasks=2
#SBATCH --partition=nodo.q

module purge
module load openmpi/4.1.1
module load gcc/12.2.1

mpicc -O3 \
    main.c \
    common/common.c \
    configuration/config.c \
    layer/layer.c \
    randomizer/randomizer.c \
    initialize/initialize.c \
    training/training.c \
    -o exec -lm

mpirun -np $SLURM_NTASKS ./exec configuration/configfile.txt
